// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicaOdontologica.API.Migrations
{
    [DbContext(typeof(ClinicaOdontologicaAPIContext))]
    [Migration("20260926010654_ArregloLlavesForaneas")]
    partial class ArregloLlavesForaneas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicaOdontologica.Cita", b =>
                {
                    b.Property<int>("idCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idCita"));

                    b.Property<string>("estadoCita")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_cita");

                    b.Property<DateTime>("fechaCita")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_cita");

                    b.Property<int>("idConsultorio")
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    b.Property<int>("idOdontologo")
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    b.Property<int>("idPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.HasKey("idCita");

                    b.HasIndex("idConsultorio");

                    b.HasIndex("idOdontologo");

                    b.HasIndex("idPaciente");

                    b.ToTable("citas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Consultorio", b =>
                {
                    b.Property<int>("idConsultorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idConsultorio"));

                    b.Property<string>("equipamientoPrincipal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("equipamiento_principal");

                    b.Property<string>("numeroSala")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_sala");

                    b.Property<int>("piso")
                        .HasColumnType("integer")
                        .HasColumnName("piso");

                    b.HasKey("idConsultorio");

                    b.ToTable("consultorios");
                });

            modelBuilder.Entity("ClinicaOdontologica.DetalleCita", b =>
                {
                    b.Property<int>("idDetalleCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idDetalleCita"));

                    b.Property<decimal>("costoAplicado")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_aplicado");

                    b.Property<int>("idCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<int>("idTratamiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("idDetalleCita");

                    b.HasIndex("idCita");

                    b.HasIndex("idTratamiento");

                    b.ToTable("detallescita");
                });

            modelBuilder.Entity("ClinicaOdontologica.Especialidad", b =>
                {
                    b.Property<int>("idEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idEspecialidad"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("nombreEspecialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_especialidad");

                    b.HasKey("idEspecialidad");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("ClinicaOdontologica.Factura", b =>
                {
                    b.Property<int>("idFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idFactura"));

                    b.Property<string>("estadoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("fechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("idCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<decimal>("impuestos")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("impuestos");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("total")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("idFactura");

                    b.HasIndex("idCita")
                        .IsUnique();

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("ClinicaOdontologica.HistorialMedico", b =>
                {
                    b.Property<int>("idHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_historial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idHistorial"));

                    b.Property<string>("alergias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alergias");

                    b.Property<string>("enfermedadesPrevias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("enfermedades_previas");

                    b.Property<int>("idPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("tipoSangre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("tipo_sangre");

                    b.HasKey("idHistorial");

                    b.HasIndex("idPaciente")
                        .IsUnique();

                    b.ToTable("historialesmedicos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Odontologo", b =>
                {
                    b.Property<int>("idOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idOdontologo"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellidos");

                    b.Property<int>("idEspecialidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("registroMedico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("registro_medico");

                    b.HasKey("idOdontologo");

                    b.HasIndex("idEspecialidad");

                    b.ToTable("odontologos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Paciente", b =>
                {
                    b.Property<int>("idPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idPaciente"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellidos");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dni");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<DateOnly>("fechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("telefono");

                    b.HasKey("idPaciente");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("ClinicaOdontologica.Receta", b =>
                {
                    b.Property<int>("idReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_receta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idReceta"));

                    b.Property<DateTime>("fechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("idCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<string>("indicaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("indicaciones");

                    b.HasKey("idReceta");

                    b.HasIndex("idCita");

                    b.ToTable("recetas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Tratamiento", b =>
                {
                    b.Property<int>("idTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTratamiento"));

                    b.Property<decimal>("costoBase")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_base");

                    b.Property<TimeOnly>("duracionEstimadaMinutos")
                        .HasColumnType("time without time zone")
                        .HasColumnName("duracion_estimada_minutos");

                    b.Property<string>("nombreTratamiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_tratamiento");

                    b.HasKey("idTratamiento");

                    b.ToTable("tratamientos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Cita", b =>
                {
                    b.HasOne("ClinicaOdontologica.Consultorio", "Consultorio")
                        .WithMany()
                        .HasForeignKey("idConsultorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Odontologo", "Odontologo")
                        .WithMany()
                        .HasForeignKey("idOdontologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("idPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Odontologo");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaOdontologica.DetalleCita", b =>
                {
                    b.HasOne("ClinicaOdontologica.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("idCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("idTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ClinicaOdontologica.Factura", b =>
                {
                    b.HasOne("ClinicaOdontologica.Cita", "Cita")
                        .WithOne("Factura")
                        .HasForeignKey("ClinicaOdontologica.Factura", "idCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ClinicaOdontologica.HistorialMedico", b =>
                {
                    b.HasOne("ClinicaOdontologica.Paciente", "Paciente")
                        .WithOne("Historial")
                        .HasForeignKey("ClinicaOdontologica.HistorialMedico", "idPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaOdontologica.Odontologo", b =>
                {
                    b.HasOne("ClinicaOdontologica.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("idEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("ClinicaOdontologica.Receta", b =>
                {
                    b.HasOne("ClinicaOdontologica.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("idCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ClinicaOdontologica.Cita", b =>
                {
                    b.Navigation("Factura");
                });

            modelBuilder.Entity("ClinicaOdontologica.Paciente", b =>
                {
                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
